version: '3.5'
services:
  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: counter
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
    restart: always
    volumes:
      - mysql:/var/lib/mysql
  demo-app:
    container_name: demo-app
    build: .
    ports:
      - "5050:5050"
    depends_on:
      - db
    restart: always
volumes:
  mysql: